#!/usr/bin/env bash
git init -qqq
git remote add origin https://github.com/aHejazi/docker-magento-237
git fetch origin -qqq
git checkout origin/master -- compose
mv compose/* ./
mv compose/.gitignore ./
mv compose/.vscode ./
rm -rf compose .git
git init

sudo apt-get install bc

# Ensure these are created so Docker doesn't create them as root
mkdir -p ~/.composer ~/.ssh
